### ISSUE TITLE
Add a way to delete content

### ISSUE THREAD

**Issue by Kjarrigan** [Flipez/static-stan#1]
As far as I can see I can upload content which creates / overrides a given path but I don't see a way to delete content. Would be really handy as sometimes you change/rename your path or just want to delete temporary files.

**Comment by Flipez** [comment]
Currently there is no authentication or verification at all. Simply adding a delete option would currently result in everyone can delete everything.

**Comment by Kjarrigan** [comment]
Thats a valid point. Maybe you could add an easy authentication mode like starting 

`stan server --token MYSECRET_KEY_FROM_AN_ENV`

and then you have to call `stan deploy/delete --token THE_SAME_AS_ABOVE`

Another thougt - how does the override work. Is the whole folder removed and then refilled with the new content or is it on a file-by-file basis? If its the former I could workaround the deletion by deploying one empty file to an old route or even an index.html with a redirect to the "new route"

**Comment by Flipez** [comment]
Yes that's what I have thought about too.

Currently the new content is simply extracted over the old one. Resulting in old files never gets deleted.

In order to resolve this issue two steps are necessary i think:
 ### Token Handling
To create a new page a token is required. If no token has been submitted one is created an returned to the user.

In order to update a page the same token as above is required. Same for deletion but the token gets now removed too.

### Cleanup
If a site is updated the old content must be removed. A deletion only triggers the cleanup and invokes a token invalidation.

**Comment by Kjarrigan** [comment]
> To create a new page a token is required. If no token has been submitted one is created an returned to the user.

That sounds like a great source for loosing access to your path because the TOKEN is lost. And I have to think about how to store the tokens in automated process.

e.g. I'm deploying my coverage report for a new branch in the CI. This triggers a TOKEN creation which I then have to store somewhere so the following CI-runs use the TOKEN and on merging I would have to remove the TOKEN from my key-store.

What about a `stan token [--remove] [TOKEN]` command which creates a new token (or accepts one sent). So I can have multiple tokens and add/remove them independently from the directory. So I could use a TOKEN for all my runs and then rotate them once a month/quarter.
